### ISSUE TITLE
Bug: google tag manager use browser page title and not screenName visible in debug mode 

### ISSUE THREAD

**Issue by Bkl741** [mib200/vue-gtm#104] opened 2020-12-02 10:50 UTC
## Info
Hi, 

I configure vue-gtm to user router. When I set debug mode I can site route name parameter in screenview log. When I set meta gtm in route, screenview has this meta as value. But for this 2 cases, browser page title is sent to google analtytics.

Configuration : 

```js
Vue.use(VueGtm, {
  id: 'GTM-XXXXX', // Your GTM single container ID or array of container ids ['GTM-xxxxxx', 'GTM-yyyyyy']
  defer: false, // defaults to false. Script can be set to `defer` to increase page-load-time at the cost of less accurate results (in case visitor leaves before script is loaded, which is unlikely but possible)
  enabled: true, // defaults to true. Plugin can be disabled by setting this to false for Ex: enabled: !!GDPR_Cookie (optional)
  debug: true, // Whether or not display console logs debugs (optional)
  loadScript: true, // Whether or not to load the GTM Script (Helpful if you are including GTM manually, but need the dataLayer functionality in your components) (optional)
  vueRouter: router, // Pass the router instance to automatically sync with router (optional)
  // ignoredViews: ['homepage'], // Don't trigger events for specified router names (case insensitive) (optional)
  trackOnNextTick: false, // Whether or not call trackView in Vue.nextTick
});
```

Log in debug mode : 

`{screenName: "Administration", path: "/Administration/Users"}`

Data sent to google analytics : dt parameter is browser page title.

Thank you for your help

| Tool   | Version       |
| ------ | ------------- |
| Plugin | v3.1.0-vue2       |
| Vue    | v2.6.11        |
| Node   | vx.x.x        |

**Comment by Shinigami92** [comment] 2020-12-02 11:05
So indeed, I found your "requested" line in code

https://github.com/mib200/vue-gtm/blob/c38e1910c20ef23d970eb76ed7fcd3b3c1467816/src/index.ts#L95

So it never was accepting a property like `screenName` 🤔 
I personally also never heard of `screenName`, is it something new?

I will manage this issue therefore as a feature-request and not a bug, hope that's ok for you 🙂

**Comment by Shinigami92** [comment] 2020-12-02 11:09
Had a quick look into `vue-router` and `vue-router-next` repos, but didn't find anything about `screenName` 🤔 
Can you please give me any sources where this is coming from?

**Comment by Bkl741** [comment] 2020-12-02 11:09
Maybe my explanation was incorrect : in browser console I can see : 
`VueGtm : Dispatching TrackView {screenName: "MyScreenTitleFromRouter", path: "/Path/MyPage"}`

In console, screenName is equal to : `const name: string = to.meta.gtm || to.name; `
but google sent browser page title : 
`https://www.google-analytics.com/g/collect?v=2&tid=G-XXXXX&gtm=345&_p=234567&sr=1920x1080&ul=fr&cid=23456&_s=3&dl=http://localhost/Page/Path&dr=http://localhost/Page/Path&dt=Browser page title&sid=4567&sct=10&seg=1&en=page_view&_et=2822`

dt query parameter isn't my route name or meta.

You can find it here : 
[vue-gtm/src/plugin.ts/](https://github.com/mib200/vue-gtm/blob/c38e1910c20ef23d970eb76ed7fcd3b3c1467816/src/plugin.ts#L79)

**Comment by Bkl741** [comment] 2020-12-02 11:13
This comes from browser console

**Comment by Shinigami92** [comment] 2020-12-02 11:26
Wait a second... Why is it calling `google-analytics`? This repo is for `googletagmanager` 👀 
Are you in the correct repo? Or am I completely confused now 😐

**Comment by Bkl741** [comment] 2020-12-02 11:27
Yes I'm in the correct repo.

I use vue-gtm and I added a google analytics tag in the google tag manager console.

**Comment by Shinigami92** [comment] 2020-12-02 11:33
Ok, I'm not so deeply into this repo cause it's created by @mib200
So how does this work? You using this plugin and added a GA Tag in the GTM Console. But how are something like the GA url is injected to be called from your code?

This plugin never injects GA but GTM. So there needs to be a second plugin in your deps.

Can you give me examples/screenshots of your vue routers object and your package.json? Or if it's open source a link to your repo?

**Comment by Shinigami92** [comment] 2020-12-02 11:36
We only have this for now: https://github.com/mib200/vue-gtm#sync-gtm-with-your-router

A parameter `dt` isn't known by us 🙁 We also don't inject this parameter in any way

**Comment by Bkl741** [comment] 2020-12-02 11:38
It's managed by google tag manager script.

When I remove vue-gtm initializaion, google anlatyics query doesn't happened

**Comment by Shinigami92** [comment] 2020-12-02 11:56
Ok, interesting ...
So to clarify what you want:
VueGtm should read `route.name` or `route.meta.gtm` and this value should be called as `...&dt=${routeName}...`?

I'm not quite sure if you maybe need to change something in your GTM Console 🤔 
I never used GA- or GTM-Console myself 🙁 
I just tookover this repo to grant maintenance, but this is the first issue I don't know enough about currently
I feel a bit sorry 😞 

So it would be very helpful to give me every information what you can give me
Like package.json deps/devDeps and examples of your routers and screenshots from your gtm/ga console
Just make sure to censore everything that's confidential

I'm now away for some time, because I'm not at home for some days but just have my Mac with me
So maybe this issue will be stretched about some days, sorry for that

**Comment by Bkl741** [comment] 2020-12-02 13:01
You're right. Maybe it's google tag manager script that override route name.

If there is something to change in gtm console, I don't know what.

**Comment by Shinigami92** [comment] 2020-12-02 13:55
I'm personally lost on this issue, and I'm sorry I cannot give you the support you deserve

Maybe StackOverflow can help you

I found this: https://stackoverflow.com/questions/56702706/how-to-pass-the-page-name-via-gtm-to-ga

So could you try to add e.g. something like `{pageTitle: ???}` via `dataLayer.push(...)`?
You can find an example in the second code block of [Documentation](https://github.com/mib200/vue-gtm#documentation)

If you open a question in StackOverflow, please copy a link into this issue

**Comment by Bkl741** [comment] 2020-12-02 13:57
No problem.

Thank you for your help.

I'll post an answer if I find the solution.

**Comment by Shinigami92** [comment] 2021-03-23 11:00
@Bkl741 did you found a solution
Also feel free to close this issue from your side :slightly_smiling_face:

**Comment by Shinigami92** [comment] 2021-04-25 09:57
If there are any further thinks, lets talk about this in the new repo(s) at https://github.com/gtm-support/vue-gtm or https://github.com/gtm-support/core

**Closed as completed by Shinigami92** 2021-04-25 09:57 UTC
Labels: enhancement, needs clarification
