### ISSUE TITLE
nonce support for Vue 2

### ISSUE THREAD

**Issue by Kooosuke** [mib200/vue-gtm#126] opened 2021-04-15 07:42 UTC
## Request / Idea
Current v3.5.0 supports nonce on configuration setting.
However v3.5.0-vue2 does not supports.
Our project is currently using Vue 2 for some reason and also need to support nonce.
Is is possible to support nonce on vue-gtm Vue 2?
...

## Additional Context

...

**Comment by Shinigami92** [comment] 2021-04-15 07:49
The behavior should be exactly the same? 

`vue-2` branch:
https://github.com/mib200/vue-gtm/blob/73d39cf1e77dfb3ed0db02dc2ca04e1aedf5965d/src/utils.ts#L32-L34

Could you check with your browser console or check if the problem is something different?

**Comment by Kooosuke** [comment] 2021-04-15 08:05
Hi Shinigami,

Thanks for you reply.
Yes, behavior should be the same.

Currently I'm using v3.5.0-vue2 and added `nonce` on configuration, however
it doesn't inject nonce to script tag.

Hope my explanation make sense to you.
Please ask me if anything is unclear.

Thank you

**Comment by Shinigami92** [comment] 2021-04-15 08:27
Is it possible to create a small reproduction repo? Then I could look into it this evening.
I have now very many meetings ^^'

**Comment by Kooosuke** [comment] 2021-04-15 09:45
Sure.

Let me create small repo for reproduction.
I will share it later.

Thank you.

**Comment by Kooosuke** [comment] 2021-04-15 10:30
Hi Shinigami,

I realized nonce is visually hidden from browser.
That's why I thought nonce is not injected at first.

```
However, recent browsers version hide nonce values that are accessed this
way (an empty string will be returned). The IDL property (script['nonce'])
will be the only way to access nonces.

Nonce hiding helps preventing that attackers exfiltrate nonce data via
mechanisms that can grab data from content attributes like this:
```
https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/nonce

I checked by accessing from console and I could see nonce value in my
source code(Vue 2).
Sorry for bothering you.
I will close this Issue.

My bad.
And thank you.

Kosuke

**Comment by Shinigami92** [comment] 2021-04-15 11:07
<img src="https://media1.tenor.com/images/9d7d9878c25d18c4b8f3fcb8df54b8f3/tenor.gif?itemid=14642704" width="200px"/>

... I think I should add this to the `README.md` 🤔

**Comment by Shinigami92** [comment] 2021-04-24 11:16
... uhm ... that's really odd, but now I found out that I never pass the `nonce` to `loadScript`

https://github.com/mib200/vue-gtm/blob/e10a9766c95220db3b261590b18b8641c0aa57b7/src/utils.ts#L12

https://github.com/mib200/vue-gtm/blob/e10a9766c95220db3b261590b18b8641c0aa57b7/src/plugin.ts#L89-L107

---

I'm so sorry XD

I'm currently in transition to move the whole code to a new repo where I can manage everything on my own
So expect a fix for this in `@gtm-support/vue-gtm`

**Comment by Shinigami92** [comment] 2021-04-24 12:12
So this is already fixed here: https://github.com/gtm-support/core/blob/9da10d8101cceab9176c68dd63c069a3b2c68c2b/src/index.ts#L180-L186

Don't know when the release will happen

**Comment by Shinigami92** [comment] 2021-04-24 16:30
@Kooosuke If you like you can test the https://www.npmjs.com/package/@gtm-support/vue2-gtm 1.0.0-alpha.1 release

There are now two packages:

- `@gtm-support/vue2-gtm` for Vue 2
- @https://github.com/gtm-support/vue-gtm for Vue 3

Both are relying on https://github.com/gtm-support/core and therefore share the same implementation!

**Closed as completed** 2021-04-25 09:53 UTC

**Comment by thilinadinith** [comment] 2022-11-08 08:05
> @Kooosuke If you like you can test the https://www.npmjs.com/package/@gtm-support/vue2-gtm 1.0.0-alpha.1 release
> 
> There are now two packages:
> 
> * `@gtm-support/vue2-gtm` for Vue 2
> * @https://github.com/gtm-support/vue-gtm for Vue 3
> 
> Both are relying on https://github.com/gtm-support/core and therefore share the same implementation!

this is not working @gtm-support/vue2-gtm for Vue 2
it gives an error as below 
<img width="655" alt="image" src="https://user-images.githubusercontent.com/11405429/200508615-f1889d9e-ad35-4e23-92b9-4cff2e75e57a.png">
